#pragma config(Motor,  port1,           left1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftArm3,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mobileLiftL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mobileLiftR,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop) // The first motor from the top-down view
#pragma config(Motor,  port7,           clawangle,     tmotorVex393_MC29, openLoop) // The second motor form the top-down view
#pragma config(Motor,  port8,           rightArm3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          right2,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton() {
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*
All of the methods listed below are used during the autonomous period
*/

int cone = 0, mobilegoal = 0; // Statically defined variables cone - 0 is for down action and 1 is for up action and same for mobilegoal
const double deviation = 2.0; // UPDATE: STILL NEED TO CHANGE VALUE TO AVOID DEVIATION DURING AUTONOMOUS

void DriveU (int amount) {
	motor[left1] = amount;
	motor[left2] = amount;
	motor[right1] = amount / deviation ;
	motor[right2] = amount / deviation;
}

void DriveD (int amount) {
	motor[left1] = -amount;
	motor[left2] = -amount;
	motor[right1] = -amount / deviation;
	motor[right2] = -amount / deviation;
}

void TurnR (int amount) {
	motor[left1] = amount;
	motor[left2] = amount;
	motor[right1] = -amount / deviation;
	motor[right2] = -amount / deviation;
}

void TurnL (int amount) {
	motor[left1] = -amount;
	motor[left2] = -amount;
	motor[right1] = amount / deviation;
	motor[right2] = amount / deviation;
}

// Opens the claw (left button on the right is to open)
void ClawU (int amount) {
	motor[claw] = -amount;
	cone = 1;
}

// Closes the claw (right button on the right is to close)
void ClawD (int amount) {
	motor[claw] = amount;
	cone = 0;
}

void StopMobileLift () {
	motor[mobileLiftL] = motor[mobileLiftR] = 0;
}

void MobileGoalU (int amount) {
	motor[mobileLiftL] = motor[mobileLiftR] = -amount;
	mobilegoal = 1;
}

void MobileGoalD (int amount) {
	motor[mobileLiftL] = motor[mobileLiftR] = amount;
	mobilegoal = 0;
}

void StopArmLift () { // Have to reset the arm motor values each time
	motor[leftArm3] = motor[rightArm3] = motor[clawangle] = 0;
}

void LiftArmU (int amount) { // Move the arm backwards
	motor[leftArm3] = -amount;
	motor[rightArm3]= -amount;
	motor[clawangle] = -75;
}

void LiftArmD (int amount) { // Move the arm forwards
	motor[leftArm3] = amount;
	motor[rightArm3]= amount;
	motor[clawangle] = 75;
}

void SetClawAngle (int amount) {
	motor[clawangle] = -amount;
}

void KeepMobileGoalU (int amount) {
	if (mobilegoal == 0) motor[mobileLiftL] = motor[mobileLiftR] = 0;
	else motor[mobileLiftL] = motor[mobileLiftR] = -amount;
}

void KeepConeU (int amount) {
	if (mobilegoal == 0) motor[mobileLiftL] = motor[mobileLiftR] = 0;
	else motor[mobileLiftL] = motor[mobileLiftR] = -amount;
}

void StopClawAngle () {
	motor[clawangle] = 0;
}

void StopClaw () {
	motor[claw] = 0;
}

void StopDrive () {
	motor[left1] = 0;
	motor[left2] = 0;
	motor[right1] = 0;
	motor[right2] = 0;
}

/*
 * Set the perfect height for the mobile goal
 * Asssume the mobile goal lifter is set all the way at the top
*/
void Set_Mobile_Goal_Height () {
	MobileGoalD(127);
	wait1Msec(230); // 230 milliseconds seems to be right
}

/*
 * Param pos = does the robot start left (0) or right (1)
 * Assume robot mobile goal lifter is already set at the perfect height before starting
 * MAKE SURE TO STOP ALL MOTORS JUST IN CASE (SET ALL ARGUMENTS BACK TO 0)
 * Currently, the robot just puts a mobile goal in the 10 point zone
 * THE STACKING-CONE FEATURE IS IMPLEMENTED AND STILL NEEDS TESTING
*/
void actual_autonomous (int pos) {
	if (pos == 0) {
		// The cone should be already placed in the claw before beginning
		LiftArmU(80);
		wait1Msec(1000);
		StopArmLift();

		// Position mobile-goal at the right height
		Set_Mobile_Goal_Height();
		StopMobileLift();

		// Drive upwards
		DriveU(127);
		wait1Msec(2400);
		DriveU(0);

		// For when robot is short of mobile goal
		DriveU(127);
		wait1Msec(100);
		DriveU(0);

		// Should have picked up the mobile-goal at this point
		MobileGoalU(127);
		wait1Msec(1000);
		StopMobileLift();

		// Stack cone onto mobile-goal
		LiftArmD(80);
		wait1Msec(1000); // May need to change amount of milliseconds
		StopArmLift();

		// Lift arm back up before driving back and placing in zone
		LiftArmU(80);
		wait1Msec(1000);
		StopArmLift();

		// Drive backwards to just in front of 1st point zone
		DriveD(127);
		wait1MSec(1800); // May need to change value of argument
		DriveD(0);

		// Turn around
		TurnR(127); // Should turn around 180 degrees right
		wait1Msec(900);
		TurnR(0);

		// Drive into zone
		DriveU(127);
		wait1Msec(800); // May need to change value of argument
		DriveU(0);

		// Unload mobile goal (with cone stacked on top)
		MobileGoalD(127);
		wait1Msec(650);
		StopMobileLift();
		DriveD(127);
		wait1Msec(500); // May need to change value of argument
		DriveD(0);

	// Uncomment this if we still have time
		/*
		// Turn around 180 degrees to face the cones
		TurnR(127);
		wait1Msec(1000);
		TurnR(0);
		*/
	} else {
		// The cone should be already placed in the claw before beginning
		LiftArmU(80);
		wait1Msec(1000);
		StopArmLift();

		// Position mobile-goal at the right height
		Set_Mobile_Goal_Height();
		StopMobileLift();

		// Drive upwards
		DriveU(127);
		wait1Msec(2400);
		DriveU(0);

		// For when robot is short of mobile goal
		DriveU(127);
		wait1Msec(100);
		DriveU(0);

		// Should have picked up the mobile-goal at this point
		MobileGoalU(127);
		wait1Msec(1000);
		StopMobileLift();

		// Stack cone onto mobile-goal
		LiftArmD(80);
		wait1Msec(1000); // May need to change amount of milliseconds
		StopArmLift();

		// Lift arm back up before driving back and placing in zone
		LiftArmU(80);
		wait1Msec(1000);
		StopArmLift();

		// Drive backwards to just in front of 1st point zone
		DriveD(127);
		wait1MSec(1800); // May need to change value of argument
		DriveD(0);

		// Turn around
		TurnL(127); // Should turn around 180 degrees left
		wait1Msec(900);
		TurnL(0);

		// Drive into zone
		DriveU(127);
		wait1Msec(800); // May need to change value of argument
		DriveU(0);

		// Unload mobile goal (with cone stacked on top)
		MobileGoalD(127);
		wait1Msec(650);
		StopMobileLift();
		DriveD(127);
		wait1Msec(500); // May need to change value of argument
		DriveD(0);

	// Uncomment this if we still have time
		/*
		// Turn around 180 degrees to face the cones
		TurnL(127);
		wait1Msec(1000);
		TurnL(0);
		*/
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

/*
 * The strategy is to be able to have the robot lift and drop 1 cone onto the mobile goal and then transport it to the first point zone
 * Still need to measure the elapsed time in seconds to check if it's at most 15 seconds
 * The stacking the cone feature has been implemented and needs to be tested
 */
task autonomous() {
	// Press Btn7L for starting on the left and Btn7R for starting on the right
	//if (vexRT[Btn7L] == 1) actual_autonomous(0);
	//else if (vexRT[BTn7R] == 1) actual_autonomous(1);
	actual_autonomous(0);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol() {
	// const double deviation = 2.0; (constant has already been statically-defined at beginning...)
	while (1) {
		/*
		<<Drive Control>>
		*/
		motor[left1] = vexRT[Ch3];
		motor[left2]= vexRT[Ch3];
		motor[right1] = vexRT[Ch2]/deviation;
		motor[right2] = vexRT[Ch2]/deviation;

		/*
		<<Claw Control>>
		*/
		if (vexRT[Btn8L]) { // Opens the claw
			motor[claw] = 30;
		}
		else if (vexRT[Btn8R]) { // Closes the claw
			motor[claw] = -60;
			wait1Msec(220); // Wait 220 milliseconds
			motor[claw] = 0;
		}

		/*
		<<Claw Arm>>
		*/
		if (vexRT[Btn6U] == 1) {
			motor[leftArm3] = -100;
			motor[rightArm3]= -100;
			motor[clawangle] = -80;
		}
		else if (vexRT[Btn6D] == 1) {
			motor[leftArm3] = 100;
			motor[rightArm3] = 100;
			motor[clawangle] = 80;
		}
		else {
			motor[leftArm3] = 0;
			motor[rightArm3] = 0;
			motor[clawangle] = 0;
		}

		/*
		<<Mobile Goal Lift>>
		*/
		if (vexRT[Btn5U]) {
			motor[mobileLiftL] = motor[mobileLiftR] = -70;
		}
		else if (vexRT[Btn5D]) {
			motor[mobileLiftR] = motor[mobileLiftL] = 70;
		}
		else {
			/*
			<<Mobile Goal Automatic Adjustment>>
			*/
			if (vexRT[Btn7R] == 1) { // Press Button 7R to automatically adjust mobile-goal
				Set_Mobile_Goal_Height();
			}
			else {
				motor[mobileLiftR] = motor[mobileLiftL] = 0;
			}
		}

		/*
		<<Claw Angle>>
		*/
		if (vexRT[Btn7U] == 1) {
			motor[clawangle] = -75;
		}
		else if (vexRT[Btn7D] == 1) {
			motor[clawangle] = 75;
		}
	}
}
