#pragma config(Motor,  port1,           left1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftArm3,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mobileLiftL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mobileLiftR,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop) // The first motor from the top-down view
#pragma config(Motor,  port7,           clawangle,     tmotorVex393_MC29, openLoop) // The second motor form the top-down view
#pragma config(Motor,  port8,           rightArm3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          right2,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton() {
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

/*
All of the methods listed below are used during the autonomus period
*/

int cone = 0, mobilegoal = 0; // Statically defined variables cone - 0 is for down action and 1 is for up action and same for mobilegoal
const double deviation = 2.0;

void DriveU (int amount) {
	motor[left1] = amount;
	motor[left2] = amount;
	motor[right1] = amount / deviation ;
	motor[right2] = amount / deviation;
}

void DriveD (int amount) {
	motor[left1] = -amount;
	motor[left2] = -amount;
	motor[right1] = -amount / deviation;
	motor[right2] = -amount / deviation;
}

void TurnR (int amount) {
	motor[left1] = amount;
	motor[left2] = amount;
	motor[right1] = -amount / deviation;
	motor[right2] = -amount / deviation;
}

void TurnL (int amount) {
	motor[left1] = -amount;
	motor[left2] = -amount;
	motor[right1] = amount / deviation;
	motor[right2] = amount / deviation;
}

// Opens the claw presumably? (left button on the right is to open)
void ClawU (int amount) {
	motor[claw] = -amount;
	cone = 1;
}

// Closes the claw presumably? (right button on the right is to close)
void ClawD (int amount) {
	motor[claw] = amount;
	cone = 0;
}

void StopMobileLift () {
	motor[mobileLiftL] = motor[mobileLiftR] = 0;
}

void MobileGoalU (int amount) {
	motor[mobileLiftL] = motor[mobileLiftR] = -amount;
	mobilegoal = 1;
	//stopMobileLift();
}

void MobileGoalD (int amount) {
	motor[mobileLiftL] = motor[mobileLiftR] = amount;
	mobilegoal = 0;
	//stopMobileLift();
}

void StopArmLift () { // Have to reset the arm motor values each time
	motor[leftArm3] = motor[rightArm3] = motor[clawangle] = 0;
}

void LiftArmU (int amount) { // Move the arm backwards
	motor[leftArm3] = -amount;
	motor[rightArm3]= -amount;
	motor[clawangle] = -75;
	//StopArmLift();
}

void LiftArmD (int amount) { // Move the arm forwards
	motor[leftArm3] = amount;
	motor[rightArm3]= amount;
	motor[clawangle] = 75;
	//StopArmLift();
}

void SetClawAngle (int amount) {
	motor[clawangle] = -amount;
}

void KeepMobileGoalU (int amount) {
	if (mobilegoal == 0) motor[mobileLiftL] = motor[mobileLiftR] = 0;
	else motor[mobileLiftL] = motor[mobileLiftR] = -amount;
}

void KeepConeU (int amount) {
	if (mobilegoal == 0) motor[mobileLiftL] = motor[mobileLiftR] = 0;
	else motor[mobileLiftL] = motor[mobileLiftR] = -amount;
}

void StopClawAngle () {
	motor[clawangle] = 0;
}

void StopClaw () {
	motor[claw] = 0;
}

void StopDrive () {
	motor[left1] = 0;
	motor[left2] = 0;
	motor[right1] = 0;
	motor[right2] = 0;
}

/*
 * Method assumes that the robot is already facing the mobile goal before autonomous begins
 * The cone should be ideally already placed in the claw either at the front or back too
 */
void Go_To_Mobile_Goal () {
	/*if (pos == 0) {
		LiftArmU(127);
		wait1Msec(600);
		DriveU(127);
		wait1Msec(1000); // May need to change value of argument
	}
	else {
		DriveU(127);
		wait1Msec(1000); // May need to change value of argument
	}*/
	LiftArmU(80);
	wait1Msec(1000);
	DriveU(127);
	wait1Msec(400);
}

/*
 * Assumes that the car has already driven.
 * Method picks up the mobile goal and then stacks the cones on top
 * Assume that the mobile goal lifter is already aligned vertically with the mobile goal
 */
void Get_Mobile_Goal () {
	MobileGoalU(127);
	wait1Msec(400); // May need to change value of argument
	LiftArmD(80);
	wait1Msec(500);
	ClawU(127); // Open claw
	wait1Msec(800);
	DriveD(127);
	wait1MSec(600);//May need to change value of argument
	LiftArmU(80);
	wait1Msec(500);
}

/*
 * Now place the mobile goal in the first point zone
 */
void Place_In_Zone () {
	TurnL(100);//Turn around 150 degrees right
	wait1Msec(800);
	DriveU(127);
	wait1Msec(600);//May need to change value of argument
	MobileGoalD(127);
	wait1Msec(650);
	DriveD(127);
	wait1Msec(500); // May need to change value of argument
}

/*
 * Set the perfect height for the mobile goal
 * Asssume the mobile goal lifter is set all the way at the top
*/
void Set_Mobile_Goal_Height () {
	MobileGoalD(127);
	// 55, 65, 41 - Take the weighted average of the 3 times
	wait1Msec(230);
}

/*
 * Param pos = does the robot start left (0) or right (1)
 * Assume robot mobile goal lifter is already set at the perfect height before starting
 * MAKE SURE TO STOP ALL MOTORS JUST IN CASE (SET ALL ARGUMENTS BACK TO 0)
 * Currently, the robot just puts a mobile goal in the 10 point zone (may decide to implement stacking cones)
*/
void actual_autonomous (int pos) {
	if (pos == 0) {
		LiftArmU(80);
		wait1Msec(1000);
		StopArmLift();
		Set_Mobile_Goal_Height();
		StopMobileLift();
		DriveU(127);
		wait1Msec(2400);
		DriveU(0);
		// Should have picked up the mobile-goal at this point
		MobileGoalU(127);
		wait1Msec(400);
		StopMobileLift();
		DriveD(127);
		wait1MSec(2400); //May need to change value of argument
		TurnR(127); //Turn around 180 degrees right
		wait1Msec(1009);
		TurnR(0);
		DriveU(127);
		wait1Msec(600); //May need to change value of argument
		DriveU(0);
		MobileGoalD(127);
		wait1Msec(650);
		StopMobileLift();
		DriveD(127);
		wait1Msec(500); // May need to change value of argument
		DriveD(0);
	} else {
		LiftArmU(80);
		wait1Msec(1000);
		StopArmLift();
		Set_Mobile_Goal_Height();
		StopMobileLift();
		DriveU(127);
		wait1Msec(2400);
		DriveU(0);
		MobileGoalU(127);
		wait1Msec(400);
		StopMobileLift();
		DriveD(127);
		wait1MSec(2400); //May need to change value of argument
		TurnL(127); //Turn around 180 degrees left
		wait1Msec(1200);
		TurnL(0);
		DriveU(127);
		wait1Msec(600); //May need to change value of argument
		DriveU(0);
		MobileGoalD(127);
		wait1Msec(650);
		StopMobileLift();
		DriveD(127);
		wait1Msec(500); // May need to change value of argument
		DriveD(0);
	}
}

/*
 * The strategy is to be able to have the robot lift and drop 1 cone onto the mobile goal and then transport it to the first point zone
 * Still need to measure the elapsed time in seconds
 * The stacking the cone feature still needs to be implemented and tested
 */
task autonomous() {
	actual_autonomous(0);
	// actual_autonomous(1);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol() {
	const double deviation = 1.6; // Set it as a constant

	while (1) {
		/*
		<<Drive Control>>
		*/
		// May have to change the constants
		/*if(vexRT[Btn6U]){
		motor[left1] = 127;
		motor[left2]= 127;
		motor[right1] = -127;
		motor[right2] = -127;
		}*/
		motor[left1] = vexRT[Ch3];
		motor[left2]= vexRT[Ch3];
		motor[right1] = vexRT[Ch2]/deviation;
		motor[right2] = vexRT[Ch2]/deviation;




		/*
		if(vexRT[Ch1] < -20 ){
		motor[left1] = vexRT[Ch1];
		motor[left2]= vexRT[Ch1];
		motor[right1] = -vexRT[Ch1];
		motor[right2] = -vexRT[Ch1];
		}
		else if(vexRT[Ch1] > 20 ){
		motor[left1] = vexRT[Ch1];
		motor[left2]= vexRT[Ch1];
		motor[right1] = -vexRT[Ch1];
		motor[right2] = -vexRT[Ch1];
		}
		else{
		motor[left1] = vexRT[Ch3];
		motor[left2]= vexRT[Ch3];
		// May need to change the constant that it divides by to ensure that it travels in a straight line
		motor[right1] = vexRT[Ch3] / deviation;
		motor[right2] = vexRT[Ch3] / deviation;
		}
		*/

		/*
		<<Claw Control>>
		*/
		if (vexRT[Btn8L]) { // Opens the claw
			motor[claw] = 30;
		}
		else if (vexRT[Btn8R]) { // Closes the claw
			motor[claw] = -60;
			wait1Msec(220); //wait 1 sec
			motor[claw] = 0;
		}


		/*
		<<Claw Arm>>
		*/
		if (vexRT[Btn6U] == 1) {
			motor[leftArm3] = -80;
			motor[rightArm3]= -80;
			motor[clawangle] = -75;
		}
		else if (vexRT[Btn6D] == 1) {
			motor[leftArm3] = 80;
			motor[rightArm3] = 80;
			motor[clawangle] = 75;
			}
		else {
			motor[leftArm3] = 0;
			motor[rightArm3] = 0;
			motor[clawangle] = 0;
		}

		/*
		<<Mobile Goal Lift>>
		*/
		if (vexRT[Btn5U]) {
			motor[mobileLiftL] = motor[mobileLiftR] = -70;
		}
		else if (vexRT[Btn5D]) {
			motor[mobileLiftR] = motor[mobileLiftL] = 70;
			/*
			wait1Msec(525);
			motor[mobileLiftR] = motor[mobileLiftL] = 0;
			*/
		}
		else {
			if (vexRT[Btn7R] == 1) {
				Set_Mobile_Goal_Height();
			}
			else {
				motor[mobileLiftR] = motor[mobileLiftL] = 0;
			}
		}



		/*
		<<Claw Angle>>
		*/
		if (vexRT[Btn7U] == 1) {
			motor[clawangle] = -75;
		}
		else if (vexRT[Btn7D] == 1) {
			motor[clawangle] = 75;
		}

		/*
		<<Mobile Goal Automatic Adjustment>>
		*/
	}
}
